services:
  accounts:
    image: "sharma/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sharmabanktest
networks:
  sharmabanktest:
    driver: "bridge"