spring:
  application:
    name: "gatewayserver"
  ## Configuration Server
  config:
    import: "optional:configserver:http://localhost:8071/"
  # Spring Cloud Properties Global Configuration
  cloud:
    gateway:
      discovery:
        ## use false, If don't want spring cloud provide Route, This will read from configuration file
        locator:
          enabled: false
        # Management properties
          lowerCaseServiceId: true
      ## Http Timeout properties
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s


# Management properties
management:
  endpoints:
    web:
      exposure:
        ## Exposing all
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

# Application Information
info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

# Application Logging
logging:
  level:
    com:
      eazybank:
        gatewayserver: DEBUG

