spring:
  application:
    name: "gatewayserver"
  ## Configuration Server
  config:
    import: "optional:configserver:http://localhost:8071/"
  # Spring Cloud Properties
  cloud:
    gateway:
      discovery:
        ## use false, If don't want spring cloud provide Route, This will read from configuration file
        locator:
          enabled: false
        # Management properties
          lowerCaseServiceId: true

# Management properties
management:
  endpoints:
    web:
      exposure:
        ## Exposing all
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

# Application Information
info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

# Application Logging
logging:
  level:
    com:
      eazybank:
        gatewayserver: DEBUG

# Resilience4j
resilience4j.circuitbreaker:
  configs:
    # this is default configuration , this will applied to all microservices
    default:
    # Specific to Account MS
    # ACCOUNTCIRCUTBREAKER:
      slidingWindowSize: 10 # How many number of request circuit breaker have to monitor before it changes the state
      permittedNumberOfCallsInHalfOpenState: 2 # Allow 2 request to Half open state
      waitDurationInOpenState: 10000 # duration in ms = 10 Sec
      failureRateThreshold: 60 #
      registerHealthIndicator: true