spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/sharmarajeshkr/sharma-config-server.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: MJiWzJYmCj2y3gpfseOfXEe5CiFicSCpxldMZ4NuswN/pCncPDffHZ5iNWghc3G5

management:
  endpoints:
    web:
      exposure:
        include: "*"
health:
  readiness-state:
    enabled: true
  liveness-state:
    enabled: true
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 8071

