server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
  # Configuration for circuitbreaker
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

# Resilience4j
resilience4j.circuitbreaker:
  configs:
    # this is default configuration, this will applied to all microservices
    default:
      slidingWindowSize: 10 # How many number of request circuit breaker have to monitor before it changes the state
      permittedNumberOfCallsInHalfOpenState: 2 # Allow 2 request to Half open state
      waitDurationInOpenState: 10000 # duration in ms = 10 Sec
      failureRateThreshold: 60 #
      registerHealthIndicator: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "loans"
    description: "Eazy Bank Loans Application"
    version: "1.0.0"