server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  config:
    activate:
      on-profile: "qa"

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  build:
    version: "2.0"

  accounts:
    message: "Welcome to EazyBank accounts"
    contactDetails:
      name: "Rajesh QA"
      email: "QA rajesh9616@gmail.com"
    onCallSupport:
      -(91)9789824976
