spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "file:///C://Users//rajes//Documents//config"
server:
  port: 8071

