build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts"
  contactDetails:
    name: "Rajesh Prod"
    email: "Prod : rajesh9616@gmail.com"
  onCallSupport:
      -(91)9789824976

