server:
  port: 8080
spring:
  application:
    name: "account"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  config:
    import: "optional:configserver:http://localhost:8071/"